/*
 * Copyright (C) 2020 pierpaolo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package di.uniba.map.b.lab.swing.esercizi;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pierpaolo
 */
public class DBFrame extends javax.swing.JFrame {

    /**
     * Creates new form DBFrame
     */
    public DBFrame() {
        initComponents();
        myInit();
    }

    private void myInit() {
        searchMenu.setEnabled(false);
        insMenu.setEnabled(false);
        dbm = new DBManager();
    }

    private DBManager dbm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        dbMenu = new javax.swing.JMenu();
        dbConnectMenuItem = new javax.swing.JMenuItem();
        insMenu = new javax.swing.JMenu();
        insItemMenuItem = new javax.swing.JMenuItem();
        insUserMenuItem = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        searchItemMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Swing DB");

        jPanel1.setPreferredSize(new java.awt.Dimension(320, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        dbMenu.setText("DB");

        dbConnectMenuItem.setText("Connect");
        dbConnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbConnectMenuItemActionPerformed(evt);
            }
        });
        dbMenu.add(dbConnectMenuItem);

        menuBar.add(dbMenu);

        insMenu.setText("Inserimento");

        insItemMenuItem.setText("Articolo...");
        insItemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insItemMenuItemActionPerformed(evt);
            }
        });
        insMenu.add(insItemMenuItem);

        insUserMenuItem.setText("Utente...");
        insUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insUserMenuItemActionPerformed(evt);
            }
        });
        insMenu.add(insUserMenuItem);

        menuBar.add(insMenu);

        searchMenu.setText("Ricerca");

        searchItemMenuItem.setText("Cerca articolo...");
        searchItemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemMenuItemActionPerformed(evt);
            }
        });
        searchMenu.add(searchItemMenuItem);

        menuBar.add(searchMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbConnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbConnectMenuItemActionPerformed
        try {
            dbm.connect();
            searchMenu.setEnabled(true);
            insMenu.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dbConnectMenuItemActionPerformed

    private void insItemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insItemMenuItemActionPerformed
        ArticoloDialog d = new ArticoloDialog(this, true);
        d.setVisible(true);
        if (d.getArticolo() != null) {
            try {
                dbm.insertArticolo(d.getArticolo());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_insItemMenuItemActionPerformed

    private void insUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insUserMenuItemActionPerformed
        UtenteDialog d = new UtenteDialog(this, true);
        d.setVisible(true);
        if (d.getUtente() != null) {
            try {
                dbm.insertUtente(d.getUtente());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_insUserMenuItemActionPerformed

    private void searchItemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemMenuItemActionPerformed
        CercaArticoloDialog d=new CercaArticoloDialog(this, dbm, true);
        d.setVisible(true);
    }//GEN-LAST:event_searchItemMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dbConnectMenuItem;
    private javax.swing.JMenu dbMenu;
    private javax.swing.JMenuItem insItemMenuItem;
    private javax.swing.JMenu insMenu;
    private javax.swing.JMenuItem insUserMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem searchItemMenuItem;
    private javax.swing.JMenu searchMenu;
    // End of variables declaration//GEN-END:variables
}
